# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'internz.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QFileDialog, QTableWidget, QTableWidgetItem, QVBoxLayout, QGridLayout)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        sizePolicy.setHorizontalStretch(400)
        sizePolicy.setVerticalStretch(400)
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/res/mainLogo4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        # self.centralwidget = QtWidgets.QWidget(MainWindow)
        # self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        # self.frame_3.setGeometry(QtCore.QRect(230, 60, 606, 451))
        self.frame_3.setGeometry(QtCore.QRect(500, 60, 1395, 750))
        # self.frame_3.resize(606, 451)
        # self.scrollArea.setWidgetResizable(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setGeometry(QtCore.QRect(500, 850, 1395, 100))
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.setSizePolicy(sizePolicy)
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(5, 5, 559, 449))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1900, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(6, 0, 331, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/res/new2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newButton.setIcon(icon1)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout_2.addWidget(self.newButton)
        self.openButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.openButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/res/open2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon2)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_2.addWidget(self.openButton)
        #self.openButton.clicked.connect(self.getfile)
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/res/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon3)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.saveasButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveasButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/res/saveas.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveasButton.setIcon(icon4)
        self.saveasButton.setObjectName("saveasButton")
        self.horizontalLayout_2.addWidget(self.saveasButton)
        self.zoominButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.zoominButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/res/zoomin.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoominButton.setIcon(icon5)
        self.zoominButton.setObjectName("zoominButton")
        self.horizontalLayout_2.addWidget(self.zoominButton)
        self.zoomoutButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.zoomoutButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/res/zoomout.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomoutButton.setIcon(icon6)
        self.zoomoutButton.setObjectName("zoomoutButton")
        self.horizontalLayout_2.addWidget(self.zoomoutButton)
        self.handButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.handButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/res/hand4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.handButton.setIcon(icon7)
        self.handButton.setObjectName("handButton")
        self.horizontalLayout_2.addWidget(self.handButton)
        self.undoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.undoButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/res/undo4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon8)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_2.addWidget(self.undoButton)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 402, 900))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 402, 450))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 402, 450))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget.setGeometry(QtCore.QRect(5, 30, 390, 415))
        self.listWidget.setObjectName("listWidget")
        self.labelLayers = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelLayers.setGeometry(QtCore.QRect(5, 5, 402, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.labelLayers.setFont(font)
        self.labelLayers.setObjectName("labelLayers")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 450, 402, 400))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 402, 400))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_4)
        self.listWidget_3.setGeometry(QtCore.QRect(5, 30, 390, 390))
        self.listWidget_3.setObjectName("listWidget_3")
        self.labelBrowser = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.labelBrowser.setGeometry(QtCore.QRect(5, 460, 402, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.labelBrowser.setFont(font)
        self.labelBrowser.setTextFormat(QtCore.Qt.PlainText)
        self.labelBrowser.setObjectName("labelBrowser")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuLayers = QtWidgets.QMenu(self.menubar)
        self.menuLayers.setObjectName("menuLayers")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuLayers.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())
        # self.graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setParent(self.frame_3)
        self.canvas.setGeometry(QtCore.QRect(3, 3, 1385, 745))
        self.canvas.setSizePolicy(sizePolicy)
        #self.canvas.setViewportUpdateMode(QtWidgets.QGraphic.FullViewportUpdate)
        self.canvas.setObjectName("canvas")
        self.toolbar = NavigationToolbar(self.canvas,self.frame_3)
        # self.frame_3.setWidgetResizable(True)
        # MainWindow.setLayout()
        # self.vert1 = QtWidgets.QHBoxLayout(self.centralwidget)
        # self.centralwidget.setLayout(self.vert1)
        # self.vert1.setWidgetResizable(True)
        self.vert = QtWidgets.QHBoxLayout(self.frame_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 0, 1395, 100))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1395, 100))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.frame_4.setLayout(self.vert)
        self.tableWidget = QTableWidget(self.scrollAreaWidgetContents_5)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1395, 100))
        self.tableWidget.setParent(self.frame_4)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PatrolGIS"))
        self.labelLayers.setText(_translate("MainWindow", "Layers"))
        self.labelBrowser.setText(_translate("MainWindow", "Browser"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuLayers.setTitle(_translate("MainWindow", "Layers"))
        self.menuHelp.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
     


import resource_rc